### ISSUE TITLE
How can i get current translation?

### ISSUE THREAD

**Issue by HazemKhaled** [hidonet/magento2-language-tr_tr#1]
Good initiative, i can see 28% done, where is the translated files

Thanks

**Comment by hidonet** [comment]
I'm working hard to complete translation. I'll upload files soon...

**Comment by hidonet** [comment]
I've updated progress to current percent. I'm working hard to complete translation. Follow me ;)

**Comment by HazemKhaled** [comment]
Wow 60%, awesome! It'll be enough to share it at least as a phase 1

**Comment by HazemKhaled** [comment]
Just done with importing all translated keys from another Magento Turkish translations into official one, (741 line)

Also @MrGekko built composer package, so i'm sure we all can do more if we work together

https://github.com/Magento2Translations/language_tr_tr

**Comment by HazemKhaled** [comment]
@hidonet We passed 65% on the other side by importing Magento 1 translations
https://github.com/Magento2Translations/language_tr_tr

check my importer script
https://github.com/HazemKhaled/Magento2i18nTools

**Comment by hidonet** [comment]
@HazemKhaled translation done ;)
